## 1. Numpy 시작하기

### Remind : 리스트

In [1]:
arr = [1, "two", 3.0]

print(arr)

[1, 'two', 3.0]


### numpy 모듈 불러오기

In [12]:
import numpy as np 

### 왜 numpy를 사용해야 할까?

In [8]:
L = range(1000)

%timeit [i** 2 for i in L] # %timeit : 실행시간 측정

311 µs ± 4.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### numpy.array

In [14]:
N = np.arange(1000)

%timeit N**2

2.25 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### numpy.array

numpyt의 Container, array

In [16]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [17]:
arr_2d = np.array([[1,2,3],[4,5,6]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr.shape #차원을 알아내는 것 

(3,)

In [19]:
arr_2d.shape

(2, 3)

## Numpy로 연산하기

### Vector와 Scalar사이의 연산

In [24]:
x = np.array([1,2,3])

x

array([1, 2, 3])

In [22]:
c = 5
c

5

In [26]:
print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행

In [27]:
y = np.array([1,3,5])
z = np.array([2,9,20])

print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## Array Indexing

python의 리스트와 유사하게 진행

In [29]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

W[0,0]

1

In [30]:
# 7을 가져오련면?
W[1,2]

7

## Array Slicing
Python의 리스트와 유사하게 진행

In [31]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 2, 3 -> 행 : 인덱스 0~1 -> [0:2]
# 6, 7 -> 열 : 인덱스 1~2 -> [1:3]

W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

## Array Broadcasting

Numpy가 연산을 진행하는 특수한 방법!

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능 하지만 
만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능합니다.
이를 **Broadcasting**이라고 합니다.


1. M * N, M * 1
M * N + M * 1 -> 이 연산을 진행 할 때 M*1 을 M * N 처럼 계산한다. / 차원을 동일하게 맞춰줌

ex)
[[1,2,3], [4,5,6], [7,8,9]] + [[0,0,0], [1,1,1], [0,0,0]]

2. M * N , 1 * N
 M * N * 1 * N -> 이 연산을 진행 할 대 1 * N 을 M * N 처럼 계산한다. / 차원을 동일하게 맞춰줌

ex)
[[1,2,3], [4,5,6], [7,8,9]] * [[0,1,-1], [0,1,-1], [0,1,-1]] = [[0,2,-3], [0,5,-6],[0,8,-9]]
* 여기서의 곱은 행렬곱이 아님!!

3. M * 1, 1* N 
 서로서로 보완하는 차원에서 Broadcasting이 진행됨
 so M * 1 -> M * N / 1 * N -> M * N 으로 
 

### 1. M by N , M by 1

In [33]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
x = np.array([0,1,0])

x = x[:, None] # x를 전치

print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N , 1 by N

In [35]:
t = np.array([1,2,3]) # 열 벡터로 바꿔줘야함 !
t = t[:, None]

u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


# Linear Algebra with Numpy

### A.bassics

### 영벡터
- 원소가 모두 0 인 벡터(행렬)
- 'np.zeros(dim)'을 통해 생성, dim은 값, 혹은 튜플(,)

In [36]:
np.zeros(3)

array([0., 0., 0.])

### 일벡터
- 원소가 모두 1인 벡터
- 'np.ones(dim)'을 통행 생성, dim은 값, 튜플(,)

In [37]:
np.ones(2)

array([1., 1.])

In [39]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 대각행렬
- Main diagonal을 제외한 성분이 0인 행렬
- 'np.diaf(main_diagnals)'을 통해 생성할 수 있음.

In [41]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [42]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 항등행렬
- Main diagonal이 1인 대각행렬
- 'np.eye()'을 통행 생성할 수 있음 .
- 'np.eye(n, (dtype = int, uint, float, complex, ....))

In [43]:
 np.eye(2) # 기본이 float

array([[1., 0.],
       [0., 1.]])

In [44]:
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

### 행렬곱
- 행렬간의 곱연산
- 'np.dot()' or '@' 사용

In [45]:
mat1 = np.array([[7,8], [9,10]])
mat2 = np.array([[1,2],[3,4]])

mat1.dot(mat2)

array([[31, 46],
       [39, 58]])

In [46]:
mat1 @ mat2

array([[31, 46],
       [39, 58]])