# Linear Algebra with Numpy

## B.Furthermore

## 트레이스
- Main diagnoal의 합
- 'np.trace()'를 사용


In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.trace()

15

## 행렬식
- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 vector의 Scaling 척도
- '**np.linalg.det()**'으로 계산

In [10]:
arr_2 = np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [11]:
np.linalg.det(arr_2)

9.000000000000002

In [14]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
np.linalg.det(arr_3)

0.0

## 역행렬
- 행렬A에 대해 AB = BA = I를 만족하는 행렬 B 
- B = A^-1
- 'np.linalg.inv()'으로 계산

In [16]:
mat = np.array([[1,4], [2,3]])

mat

array([[1, 4],
       [2, 3]])

In [19]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [20]:
mat @ mat_inv

array([[1., 0.],
       [0., 1.]])

## 고유값과 고유벡터
- 정방행렬(nXn) A에 대해서 
- 'np.linalg.eig()'으로 계산

In [22]:
mta = np.array([[2,0,-2],[1,1,-2], [0,0,1]])

mta

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [23]:
np.linalg.eig(mta)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))